# Generated by Django 2.2.7 on 2019-12-21 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_at', models.DateField()),
                ('complete_by', models.DateField()),
                ('tag', models.IntegerField(choices=[(0, 'CAN DO'), (1, 'CAN PLAY'), (2, 'CAN GO'), (3, 'CAN MAKE'), (4, 'CAN EAT')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_at', models.DateField()),
                ('review', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real.Dream')),
            ],
        ),
    ]
