# Generated by Django 2.2.7 on 2019-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
