# Generated by Django 2.2.7 on 2019-11-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_auto_20191123_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='dream',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real.Dream'),
        ),
    ]
